# .streamlit/secrets.toml
#
# Add your API keys and secrets here for Streamlit Community Cloud deployment.
# DO NOT commit real secrets to version control!

OPENAI_API_KEY = "your-openai-api-key-here"
TWILIO_ACCOUNT_SID = "your-twilio-account-sid-here"
TWILIO_AUTH_TOKEN = "your-twilio-auth-token-here"
TWILIO_PHONE_NUMBER = "+1xxxxxxxxxx" 